# Generated by Django 3.1 on 2021-05-31 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='city_name',
            new_name='name',
        ),
    ]
